#!/usr/bin/env python3
from __future__ import annotations

import argparse
import difflib
from collections import defaultdict
from pathlib import Path
from typing import Any

import yaml

ROOT = Path(__file__).resolve().parents[1]
CONTEXT = ROOT / "context"
GENERATED_HEADER = "<!-- generated by tools/build_context_indexes.py; do not edit manually -->"


def parse_frontmatter(path: Path) -> dict[str, Any]:
    text = path.read_text(encoding="utf-8")
    if not text.startswith("---\n"):
        return {}
    end = text.find("\n---", 4)
    if end == -1:
        return {}
    data = yaml.safe_load(text[4:end]) or {}
    return data if isinstance(data, dict) else {}


def context_files() -> list[Path]:
    files = []
    for path in CONTEXT.rglob("*.md"):
        if path.name == "log.md" or path.name.startswith("index"):
            continue
        files.append(path)
    return sorted(files)


def rel(path: Path) -> str:
    return path.relative_to(ROOT).as_posix()


def markdown_link(target: Path, output: Path) -> str:
    return target.relative_to(output.parent).as_posix()


def title_for(path: Path, meta: dict[str, Any]) -> str:
    return str(meta.get("title") or path.stem.replace("-", " ").title())


def list_index(entries: list[tuple[str, Path]], output: Path) -> str:
    lines = [GENERATED_HEADER, ""]
    for title, path in sorted(entries, key=lambda item: (item[0].lower(), rel(item[1]))):
        lines.append(f"- [{title}]({markdown_link(path, output)})")
    lines.append("")
    return "\n".join(lines)


def grouped_index(groups: dict[str, list[tuple[str, Path]]], heading: str, output: Path) -> str:
    lines = [GENERATED_HEADER, "", f"# {heading}", ""]
    for group in sorted(groups, key=str.lower):
        lines.extend([f"## {group}", ""])
        for title, path in sorted(groups[group], key=lambda item: (item[0].lower(), rel(item[1]))):
            lines.append(f"- [{title}]({markdown_link(path, output)})")
        lines.append("")
    return "\n".join(lines)


def build_indexes() -> dict[Path, str]:
    metas: list[tuple[Path, dict[str, Any]]] = [(path, parse_frontmatter(path)) for path in context_files()]
    title_by_rel_path = {rel(path): title_for(path, meta) for path, meta in metas}

    by_skill: dict[str, list[tuple[str, Path]]] = defaultdict(list)
    by_role: dict[str, list[tuple[str, Path]]] = defaultdict(list)
    by_project: dict[str, list[tuple[str, Path]]] = defaultdict(list)
    by_date: dict[str, list[tuple[str, Path]]] = defaultdict(list)
    by_target: dict[str, list[tuple[str, Path]]] = defaultdict(list)

    for path, meta in metas:
        title = title_for(path, meta)
        for skill in meta.get("skills") or ["Unspecified"]:
            by_skill[str(skill)].append((title, path))
        for role in meta.get("related_roles") or []:
            role_key = str(role)
            by_role[title_by_rel_path.get(role_key, role_key)].append((title, path))
        if meta.get("type") == "project":
            by_project[str(meta.get("company") or "other")].append((title, path))
        by_date[str(meta.get("date_start") or "undated")].append((title, path))
        for target in meta.get("resume_relevance") or ["general"]:
            by_target[str(target)].append((title, path))

    by_skill_path = CONTEXT / "index-by-skill.md"
    by_role_path = CONTEXT / "index-by-role.md"
    by_project_path = CONTEXT / "index-by-project.md"
    by_date_path = CONTEXT / "index-by-date.md"
    by_target_path = CONTEXT / "index-by-target-role.md"

    return {
        by_skill_path: grouped_index(by_skill, "Context By Skill", by_skill_path),
        by_role_path: grouped_index(by_role, "Context By Role", by_role_path),
        by_project_path: grouped_index(by_project, "Context By Project", by_project_path),
        by_date_path: grouped_index(by_date, "Context By Date", by_date_path),
        by_target_path: grouped_index(by_target, "Context By Target Role", by_target_path),
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    desired = build_indexes()
    failed = False
    for path, content in desired.items():
        content = content.rstrip() + "\n"
        if args.check:
            current = path.read_text(encoding="utf-8") if path.exists() else ""
            if current != content:
                print(f"Stale generated index: {rel(path)}")
                for line in difflib.unified_diff(
                    current.splitlines(), content.splitlines(), fromfile="current", tofile="expected", lineterm=""
                ):
                    print(line)
                failed = True
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
            print(rel(path))
    return 1 if failed else 0


if __name__ == "__main__":
    raise SystemExit(main())
